### ISSUE TITLE
Identify maximum set of TSO-s for CGM

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#142]
Identify TSO-s to be included, that results in a stable CGM, to achieve stable daily process

**Comment by MK1295** [comment]
EXCLUDE areas :
DKE, DKW, FR, D2, D4, D7, D8, AT, if needed also SI
Issues with SI IGMs - denied CGMs due to Kirchhoff’s First Law issue – solved and verified on TST environment, waiting deployment on PROD 
Issues for D2, D8 - CGM divergence, issue with equivalent branches – solved but HF not yet available for testing on TST environment [SCC]
RTEFRANCE creates divergence issues for most TSs [SELENECC]

**Comment by Haigutus** [comment]
1. Can you also provide currently known good set of IGM-s?
2. Any ideas how to identify those issues during the IGM validation?

**Comment by Haigutus** [comment]
On point 2., check sum flow per TP node in IGM validation, after the LF step. To exclude models with Powerflow and Topology issue

**Comment by MK1295** [comment]
Include :
APG,AST,CEPS,CGES,CREOS,D4,EMS,ESO,HOPS,IPTO,LITGRID,NOSBIH,OST,PSE,REE,REN,SEPS,TRANSELECTICA,ELERING,MAVIR,SWISSGRID,

Exclude:
ELES,ELIA,DKE,DKW (Occasional errors)
RTEFRANCE,TERNA(Localized errros)
50Hertz,TTG,D7 (propagating erros)

UNDER DISCUSSION: 
**FINGRID https://github.com/Baltic-RCC/EMF/tree/mr-open-nonretained-switches-connecting-tns
(Checking problamtic switched and feed it to loadflow, the changed model will not be used in the post-processing, and this solution would be temporary if it will be implemented in validation)**
